Support for Erasure Coded pools fio benchmarking
openstack-charmers/charm-woodpecker pull request #3
Opened 2022-10-18 15:23 UTC by gustavosr98

Fixes [LP#194078: Need support for EC pools](https://bugs.launchpad.net/charm-woodpecker/+bug/1940478)

This patch adds optional parameter `ec-pool-name` to juju fio action. In case it is set then it is passed to rbd image creation command as an additional parameter `--data-pool <ec-pool-name>`

Since the rbd image can be created in different pools, this patch removes the rbd image if existing before creation.     

### Compiling and deploying
Required resource snap
```bash
git clone https://github.com/openstack-charmers/snap-swift-bench
cd snap-swift-bench
snapcraft --use-lxd
```

Deploying charm
```bash
# Ceph deployed
charmcraft pack
juju deploy ./woodpecker_ubuntu-20.04-amd64-s390x-ppc64el-arm64_ubuntu-22.04-amd64-s390x-ppc64el-arm64.charm woodpecker-gisr --to lxd:2 --bind oam
juju attach-resource woodpecker-gisr swift-bench=../snap-swift-bench/swift-bench_1.0_amd64.snap
juju add-relation woodpecker-gisr:prometheus-target  prometheus:target
juju add-relation woodpecker-gisr:ceph-client ceph-mon:client   
```

### Create EC pool
```bash
juju ssh ceph-mon/leader 

sudo su
K=6
M=3
FAILURE_DOMAIN=osd # AZ (osd|host|rack)
EC_POOL=ecpool_k${K}_m${M}

ceph osd pool create ${EC_POOL} erasure ${EC_POOL}_profile
ceph osd pool set $EC_POOL allow_ec_overwrites true
ceph osd pool application enable $EC_POOL rbd
```

### Run FIO benchmarks
```bash
JOBS_PER_DISK=5
RUNTIME=300
# EC Pool
juju run-action --wait woodpecker-gisr/leader fio \                
   operation=randwrite block-size=4k num-jobs=$JOBS_PER_DISK runtime=$RUNTIME ec-pool-name=$EC_POOL
juju run-action --wait woodpecker-gisr/leader fio \
   operation=write block-size=4M num-jobs=$JOBS_PER_DISK runtime=$RUNTIME ec-pool-name=$EC_POOL

# RP pool
juju run-action --wait woodpecker-gisr/leader fio \                
   operation=randwrite block-size=4k num-jobs=$JOBS_PER_DISK runtime=$RUNTIME
juju run-action --wait woodpecker-gisr/leader fio \
   operation=write block-size=4M num-jobs=$JOBS_PER_DISK runtime=$RUNTIME
   
```

Benchmark outputs
> Left is EC 9+3. Right is default RP pool created by charm

1. randwrite/4k

![Screenshot from 2022-10-17 22-31-06](https://user-images.githubusercontent.com/40648663/196468281-70e3398b-f662-44dc-a7a5-ba39f4830244.png)

2. write/4M

![Screenshot from 2022-10-17 22-43-54](https://user-images.githubusercontent.com/40648663/196473211-78e5080a-d11b-4bb2-9a5d-681e4c1d89b0.png)

2022-10-18 15:47 UTC, lmlg requested changes

2022-10-18 15:47 UTC, lmlg commented on src/charm.py
> +            if "No such file or directory" in e.stderr.decode("UTF-8"):
I think it would be much more robust if you compared the exception's return code (In this case, I think it would be `ENOENT`).

2022-10-18 15:47 UTC, lmlg commented on src/charm.py
> +                event.set_results({"stderr": _msg, "code": "1"})
This is probably redundant. If you've called `event.fail`, there's no further need to set results; the client already knows what it needs to know.

2022-10-18 22:18 UTC, gustavosr98 commented
@lmlg thanks for the comments

2022-10-19 17:38 UTC, lmlg approved these changes
LGTM

2022-10-19 20:24 UTC, merged